[package]
name = "pssstt"
authors = ["vats", "clint"]
version = "0.1.0"
edition = "2021"

[dependencies]
clippy = "0.0.302"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
zmq = "0.10.0"
